name: Deploy Kong Config

on:
  push:
    branches:
      - dev
      - uat
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.55.2/deck_1.55.2_linux_amd64.tar.gz | tar -xz
          sudo mv deck /usr/local/bin/deck

      - name: Select Control Plane based on branch
        id: cp
        run: |
          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
            echo "CP_NAME=${{ secrets.KONNECT_CP_NAME_DEV }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "uat" ]; then
            echo "CP_NAME=${{ secrets.KONNECT_CP_NAME_UAT }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "prod" ]; then
            echo "CP_NAME=${{ secrets.KONNECT_CP_NAME_PROD }}" >> $GITHUB_ENV
          fi

      - name: Validate Kong config
        run: |
          deck file validate api/kong.yaml

      - name: Deploy to Konnect
        run: |
          deck gateway sync api/kong.yaml \
            --konnect-token "${{ secrets.KONNECT_TOKEN }}" \
            --konnect-control-plane-name "$CP_NAME" \
            --konnect-addr https://me.api.konghq.com \
            --yes
